### PR TITLE
Break up guide into separate documents.

### PR DESCRIPTION
**Pull request by sausagejohnson**
* Move nexys appendix into its own guide.
* Break out heavy topics into the beginnings of a reference guide
* Common header and footer for all documents so all guide styles and includes stay in sync
* New sandbox document for rapid typesetting which can be built without the makefile
* Updated Makefile so a specific guide can be built on the command line
* Updated readme guide for the makefile changes

### CODE REVIEW

**Comment by Edilbert** [comment]
I agree with your proposed break up. The current user's guide is growing too big.
But I think, it is Paul's right to decide.

**Comment by sausagejohnson** [comment]
Absolutely. Thanks @Edilbert

**Comment by gardners** [comment]
Hello all,

So Detlef and I were just talking about this. We need a shorter manual for
the printed one to go in the pre-series.  There is no need for the nexys
stuff in there, since it is for the real hardware.

What I suggest is that we have multiple top-level files, cloned from
userguide.tex, with one for the preseries, one for the longer user guide
that is hardware agnostic, and another which is the programmer's reference
guide, that has everything in it.

Paul.

**Comment by sausagejohnson** [comment]
I'll get in touch on chat to see where this is at.

**Comment by gardners** [comment]
Here is the revised plan:

I think we need four books:

1. User Guide (for preseries printing initially)
2. Reference Guide (userguide + all hardware-independent stuff + M65 real computer relevant stuff)
3. Hardware Tinkerer's Guide (with all hardware related things)
4. The MEGA65 Book that is the union of all of the above.

Use \part{} in the bigger books where required to group content.

**Comment by sausagejohnson** [comment]
Changes are in + extra mega65-book.

**Pull request merged**
