### PR TITLE
more verbose version of the basic program, using more basic features

### PR DESCRIPTION
**Pull request by lydon42**
I'm currently testing out some example from the user guide in xemu. There are a lot of examples that are... _suboptimal_. So I thought I could give one an upgrade, perhaps I'll do more if this is something worthwhile doing...

I think the BASIC in the users manual should be
- easy to read (use more SPACE, no keyword spaghetti code)
- have lots of comments (use more REM on extra lines)
- should not use obscure logic (if you want to toggle a bit use the bit toggling operator also known as XOR)
- introduce the reader to features of BASIC65 (perhaps some ELSE?)

It would be nice if there was a style that allowed for highlighting as the MEGA65 does. But my TeX skills are not as mad as they where 30 years ago...

Please drop me some comment if I should pursue this...

### CODE REVIEW

**Review by Edilbert — CHANGES_REQUESTED** [review]
Hi Oliver,
thank you very much for your contribution, which is appreciated.
The BASIC manual is a mixture of text and examples from several authors.
I'm busy to consolidate and harmonize the text before printing.
I agree with you, that we should use MEGA65 features and rich comments.
I'll merge your pull request, but have one request:
Can you please replace the decimal addresses, used in PEEK and POKE with hex constants of the form $nnnn ? Numeric hex constants are also a feature of the MEGA65 and make it much easier to see, which I/O registers are addressed.

**Comment by lydon42** [comment]
I formatted some more basic code and switched to hex in most examples.

The multicolor sprite example at the end is broken. There are two FOR I loops in 716/717, I have not yet figured out what they really should do (have to understand how the sprites work first...)

**Comment by Edilbert** [comment]
Thank you very much

**Comment by lydon42** [comment]
Oh, that was fast...

Logic wise there has to be a next i at the end of the line with the first next i... or is this implied in that case?

For me (xemu with 920220) the sprite looks really broken and the pokes seem to go to screen memory... which seems odd as AD is initialized with something less than 1000...

**Comment by Edilbert** [comment]
The index after NEXT is optional and may be omitted.
I'll look later at this issue.

**Comment by lydon42** [comment]
Well, sure, the var after next is optional. But the next after the for isn't...

I think the program does not work because the moving of the sprite table is missing from the program. There is a snippet a bit higher in the chapter which does this, but it is missing from the program...

For me: line numbers == a thing I can type in and then it works.

Here: please first type in all examples from the chapter, then program will work... 

Tidying up now...

BTW: I am inclined to go over more BASIC in the book.

**Comment by Edilbert** [comment]
Very well. Every help is appreciated and needed, so go ahead.

**Pull request merged**
