### PR TITLE
Extend the descriptions of the hypervisor services

### PR DESCRIPTION
**Pull request by jimnicholls**
- [x] Create a new layout modeled on the BASIC65 command reference.
- [x] Move the existing content into the new layout
- [x] Add extra information to the services.

### CODE REVIEW

**Comment by jimnicholls** [comment]
Hi @gardners, I've created this draft pull request for the work I'm doing on the Hypervisor services in the MEGA65 book.
I did much less than I hoped. Life got in the way.

**Comment by jimnicholls** [comment]
Some changes I've made from the previous chapter.
- In the subsection title, I've used the short theoretical labels a programmer might use for the services. 
- I removed the $off:$a notation and replaced it the LDA:STA:CLV instructions needed to trigger the trap. This to offload having to remember the trap base is $D640 from the programmer, and to remind them they need the CLV after the STA.

**Comment by jimnicholls** [comment]
I've completed a first pass over the drive/storage services.
Before I move on, I want to experiment with breaking this section down. I'm guessing two three: drives, directories, files.

**Review by gardners — APPROVED** [review]

**Comment by jimnicholls** [comment]
The existing content as been removed and the old appendix has been removed.

Some other changes:
- The introduction has been expanded to include an explanation of what the hypervisor is.
- The term HYPPO is used to refer to the Hypervisor.
- The hdos_ prefix has been changed to hyppo_. This is mostly because not all the services are related to HDOS and from the programmer's perspective it doesn't matter if a service is related to HDOS or some other part of Hyppo.
- The HYPPO error codes have been added to the index.

**Comment by jimnicholls** [comment]
I would really appreciate it if someone could look over the examples. They work. But I might have written some embarrassing code.

**Pull request merged**
