### PR TITLE
Add missing documentation of the RTC

### PR DESCRIPTION
**Pull request by eilers**
This is work in progress.
I've added the missing documentation of the RTC-Chip. It was not shown at all ...

### CODE REVIEW

**Comment by dansanderson** [comment]
Thanks for starting this! Would you like me to merge this and take over, or do you want to flesh it out a bit first?

I have an example of reading the RTC in a recent Digest: https://dansanderson.com/mega65/kernal-of-truth/

**Comment by eilers** [comment]
> Thanks for starting this! Would you like me to merge this and take over, or do you want to flesh it out a bit first?
This is a draft of a pull request, which is just to show that I am currently working on it. I will change it to a real pull request when I think that it is worth to be reviewed. :)

**Comment by eilers** [comment]
I finalized the documentation. 
And as the doc-comments in the mega65-core are now merged into the development branch, I think we are ready to merge this one here, too.

**Comment by eilers** [comment]
Hi @dansanderson,
I think this documentation update is good to go. I would be happy to see this merged. 

Thanks a lot! :)

**Comment by dansanderson** [comment]
Merged. This might get reorg'd and expanded a bit as the books are edited but this adds value as is for now. Thanks very much!

**Pull request merged**
