### PR TITLE
Fix of multi-colour sprite example (VIC appendix)

### PR DESCRIPTION
**Pull request by lydon42**
This is my fix for the mc-sprite example.

Notes:
- there was a second AD definition in line 20 setting AD to 0x340. This did not work for me.
- AD is set to 0xe00 in line 0. This is in screen ram... it could be for the example, so you can type around, ok for me
- the decode loop was no good example, I fixed it to be more teaching and less confusing
- transparent color was listed as @ in the data, but the start did set it to colour 10 (J)
- what exactly depicted this sprite? so... everyone likes a kissy smiley!

In a xemu-merger with 920220, freshly booted, it looks like this:

### CODE REVIEW

**Comment by lydon42** [comment]
Some more changes:
- clear screen
- transparent colour as variable
- set sprite to transparent at start instead of black

**Comment by lydon42** [comment]
Oh, the screenoutput style does not break at page end... so... split this in two parts?

**Comment by lydon42** [comment]
A suitable fix for the long screenoutput.

Where can I find MEGA65GraphicSymbols.otf? It is not in the repo. And my build fails at 
`l.323 \input{regtable_FDC.C65}`
Am I missing something in my environment to get a working build of the doc?

**Comment by lydon42** [comment]
Ok, testing with the sandbox helps. Still curious why I am missing regtables. Perhaps I need some olther repo (core?) in a different branch than main?

About the break of the box: breaking by hand is bad. But I don't feel like fiddeling with LaTeX styles. BTW: In my tests I ended up with the next heading directly beneath the basic box, with nothing below it... this also looks like something is missing style wise. Or it has to do with heading-longtable interaction... dont' know.

**Comment by Edilbert** [comment]
Thank you very much

**Pull request merged**
